apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: manual-payments
spec:
  schedule: "0 0 */2 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: manual-payments
            image: gcr.io/buffer-data/manual-payments:0.3.0
            volumeMounts:
              - name: googlesheets-token
                mountPath: /scripts/google
                readOnly: true
            env:
              - name: REDSHIFT_DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: database
              - name: REDSHIFT_USER
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: user
              - name: REDSHIFT_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: endpoint
              - name: REDSHIFT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: password
              - name: REDSHIFT_DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: port
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                      name: aws
                      key: access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                      name: aws
                      key: secret-access-key
              - name: AWS_DEFAULT_REGION
                valueFrom:
                  secretKeyRef:
                      name: aws
                      key: default-region
            imagePullPolicy: Always
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dockerhub
          volumes:
          - name: googlesheets-token
            secret:
              secretName: googlesheets
              items:
              - key: token-rds
                path: googlesheets_token.rds
